#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|tsx)$' | xargs -r npx eslint || exit 1
git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|tsx|json|css|md)$' | xargs -r npx prettier --check || exit 1
